틀린 것 비교

In [50]:
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

데이터 불러오기

In [39]:
PVP0_array = np.load('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data3/labeling/hard_label/hard_label_PVP0.npy')
PVP1_array = np.load('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data3/labeling/hard_label/hard_label_PVP1.npy')
PVP2_array = np.load('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data3/labeling/hard_label/hard_label_PVP2.npy')
PVP3_array = np.load('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data3/labeling/hard_label/hard_label_PVP3.npy')
PVP4_array = np.load('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data3/labeling/hard_label/hard_label_PVP4.npy')
PVP5_array = np.load('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data3/labeling/hard_label/hard_label_PVP5.npy')
PVP6_array = np.load('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data3/labeling/hard_label/hard_label_PVP6.npy')
PVP7_array = np.load('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data3/labeling/hard_label/hard_label_PVP7.npy')
PVP8_array = np.load('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data3/labeling/hard_label/hard_label_PVP8.npy')
PVP9_array = np.load('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data3/labeling/hard_label/hard_label_PVP9.npy')

In [40]:
PVP0_array

array([1, 2, 1, ..., 1, 1, 2], dtype=int64)

In [41]:
PVP0_array = np.where(PVP0_array == 1, 0, np.where(PVP0_array == 2, 1, PVP0_array))
PVP1_array = np.where(PVP1_array == 1, 0, np.where(PVP1_array == 2, 1, PVP1_array))
PVP2_array = np.where(PVP2_array == 1, 0, np.where(PVP2_array == 2, 1, PVP2_array))
PVP3_array = np.where(PVP3_array == 1, 0, np.where(PVP3_array == 2, 1, PVP3_array))
PVP4_array = np.where(PVP4_array == 1, 0, np.where(PVP4_array == 2, 1, PVP4_array))
PVP5_array = np.where(PVP5_array == 1, 0, np.where(PVP5_array == 2, 1, PVP5_array))
PVP6_array = np.where(PVP6_array == 1, 0, np.where(PVP6_array == 2, 1, PVP6_array))
PVP7_array = np.where(PVP7_array == 1, 0, np.where(PVP7_array == 2, 1, PVP7_array))
PVP8_array = np.where(PVP8_array == 1, 0, np.where(PVP8_array == 2, 1, PVP8_array))
PVP9_array = np.where(PVP9_array == 1, 0, np.where(PVP9_array == 2, 1, PVP9_array))

In [42]:
PVP0_array

array([0, 1, 0, ..., 0, 0, 1], dtype=int64)

In [43]:
df_unlabeled = pd.read_csv("C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data3/df_unlabeled.csv")

In [44]:
unlabel_array = np.array(df_unlabeled["label"])

In [45]:
unlabel_array= np.where(unlabel_array == 1, 0, np.where(unlabel_array == 2, 1, unlabel_array))

In [46]:
unlabel_array

array([0, 1, 0, ..., 0, 1, 1], dtype=int64)

하나의 array로 만들기

In [47]:
all_array = np.array([unlabel_array,
                      PVP0_array,
                      PVP1_array,
                      PVP2_array,
                      PVP3_array,
                      PVP4_array,
                      PVP5_array,
                      PVP6_array,
                      PVP7_array,
                      PVP8_array,
                      PVP9_array,])

In [58]:
cosine_sim = cosine_similarity(all_array)


In [63]:
cosine_sim[1]

array([0.88532718, 1.        , 0.89486663, 0.8579387 , 0.882677  ,
       0.90267467, 0.90029055, 0.86895703, 0.77424635, 0.66601045,
       0.8368019 ])

In [68]:
all_index = ['origin',
           'PVP0',
           'PVP1',
           'PVP2',
           'PVP3',
           'PVP4',
           'PVP5',
           'PVP6',
           'PVP7',
           'PVP8',
           'PVP9']

In [71]:
df_all_vectors = pd.DataFrame(cosine_sim, columns=all_index)

In [79]:
df_all_vectors = df_all_vectors.set_index(pd.Index(all_index))

In [80]:
df_all_vectors

origin      PVP0      PVP1      PVP2      PVP3      PVP4      PVP5  \
origin  1.000000  0.885327  0.936382  0.947849  0.966413  0.948497  0.965766   
PVP0    0.885327  1.000000  0.894867  0.857939  0.882677  0.902675  0.900291   
PVP1    0.936382  0.894867  1.000000  0.903045  0.936703  0.944135  0.950947   
PVP2    0.947849  0.857939  0.903045  1.000000  0.956700  0.914285  0.934722   
PVP3    0.966413  0.882677  0.936703  0.956700  1.000000  0.942402  0.965098   
PVP4    0.948497  0.902675  0.944135  0.914285  0.942402  1.000000  0.963521   
PVP5    0.965766  0.900291  0.950947  0.934722  0.965098  0.963521  1.000000   
PVP6    0.930408  0.868957  0.930400  0.913265  0.934560  0.926446  0.935319   
PVP7    0.797680  0.774246  0.809900  0.766980  0.793637  0.813261  0.811067   
PVP8    0.733662  0.666010  0.695592  0.768016  0.740579  0.704676  0.720122   
PVP9    0.854331  0.836802  0.855774  0.828664  0.850291  0.867900  0.863226   

            PVP6      PVP7      PVP8      PVP9  
origin  0.930408  0.797680  0.733662  0.854331  
PVP0    0.868957  0.774246  0.666010  0.836802  
PVP1    0.930400  0.809900  0.695592  0.855774  
PVP2    0.913265  0.766980  0.768016  0.828664  
PVP3    0.934560  0.793637  0.740579  0.850291  
PVP4    0.926446  0.813261  0.704676  0.867900  
PVP5    0.935319  0.811067  0.720122  0.863226  
PVP6    1.000000  0.815003  0.712653  0.858175  
PVP7    0.815003  1.000000  0.591514  0.793506  
PVP8    0.712653  0.591514  1.000000  0.642559  
PVP9    0.858175  0.793506  0.642559  1.000000

In [81]:
all_vectors_writer = pd.ExcelWriter('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data3/result/all_vectors.xlsx', engine='xlsxwriter')

In [82]:
df_all_vectors.to_excel(all_vectors_writer, sheet_name='only_cosine', index=True)

In [83]:
all_vectors_writer.save()

C:\Users\user\AppData\Local\Temp\ipykernel_22492\1541263730.py:1: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  all_vectors_writer.save()
