In [14]:
import numpy as np
import pandas as pd

In [15]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix

데이터 불러오기

In [16]:
PVP0_array = np.load('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data3/labeling/hard_label/hard_label_PVP0.npy')
PVP1_array = np.load('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data3/labeling/hard_label/hard_label_PVP1.npy')
PVP2_array = np.load('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data3/labeling/hard_label/hard_label_PVP2.npy')
PVP3_array = np.load('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data3/labeling/hard_label/hard_label_PVP3.npy')
PVP4_array = np.load('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data3/labeling/hard_label/hard_label_PVP4.npy')
PVP5_array = np.load('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data3/labeling/hard_label/hard_label_PVP5.npy')
PVP6_array = np.load('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data3/labeling/hard_label/hard_label_PVP6.npy')
PVP7_array = np.load('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data3/labeling/hard_label/hard_label_PVP7.npy')
PVP8_array = np.load('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data3/labeling/hard_label/hard_label_PVP8.npy')
PVP9_array = np.load('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data3/labeling/hard_label/hard_label_PVP9.npy')

In [17]:
PVP0_array = np.where(PVP0_array == 1, 0, np.where(PVP0_array == 2, 1, PVP0_array))
PVP1_array = np.where(PVP1_array == 1, 0, np.where(PVP1_array == 2, 1, PVP1_array))
PVP2_array = np.where(PVP2_array == 1, 0, np.where(PVP2_array == 2, 1, PVP2_array))
PVP3_array = np.where(PVP3_array == 1, 0, np.where(PVP3_array == 2, 1, PVP3_array))
PVP4_array = np.where(PVP4_array == 1, 0, np.where(PVP4_array == 2, 1, PVP4_array))
PVP5_array = np.where(PVP5_array == 1, 0, np.where(PVP5_array == 2, 1, PVP5_array))
PVP6_array = np.where(PVP6_array == 1, 0, np.where(PVP6_array == 2, 1, PVP6_array))
PVP7_array = np.where(PVP7_array == 1, 0, np.where(PVP7_array == 2, 1, PVP7_array))
PVP8_array = np.where(PVP8_array == 1, 0, np.where(PVP8_array == 2, 1, PVP8_array))
PVP9_array = np.where(PVP9_array == 1, 0, np.where(PVP9_array == 2, 1, PVP9_array))

In [18]:
df_unlabeled = pd.read_csv("C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data3/df_unlabeled.csv")

In [19]:
unlabel_array = np.array(df_unlabeled["label"])

In [20]:
unlabel_array= np.where(unlabel_array == 1, 0, np.where(unlabel_array == 2, 1, unlabel_array))

In [21]:
all_array = np.array([PVP0_array,
                      PVP1_array,
                      PVP2_array,
                      PVP3_array,
                      PVP4_array,
                      PVP5_array,
                      PVP6_array,
                      PVP7_array,
                      PVP8_array,
                      PVP9_array])

# accuracy, precision, recall, f1

In [22]:
accuracy_list = []
precision_list = []
recall_list = []
f1_list = []

for i in all_array:
    accuracy = accuracy_score(unlabel_array, i)
    precision = precision_score(unlabel_array, i)
    recall = recall_score(unlabel_array, i)
    f1 = f1_score(unlabel_array, i)
    
    accuracy_list.append(accuracy)
    precision_list.append(precision)
    recall_list.append(recall)
    f1_list.append(f1)

# specificity

In [31]:
cm_list = []
for i in all_array:
    cm = confusion_matrix(unlabel_array, i)
    cm_list.append(cm)

In [34]:
specificity_list = []
for i in cm_list:
    tn, fp, fn, tp = i.ravel()
    specificity = tn / (tn + fp)
    specificity_list.append(specificity)

In [35]:
specificity_list

[0.9768041237113402,
 0.9877577319587629,
 0.8788659793814433,
 0.9497422680412371,
 0.9873281786941581,
 0.9819587628865979,
 0.9540378006872853,
 0.9924828178694158,
 0.018900343642611683,
 0.978307560137457]

# Matthews Correlation Coefficient (MCC)

In [27]:
mcc_list = []
for i in cm_list:
    tn, fp, fn, tp = i.ravel()
    mcc = (tp * tn - fp * fn) / np.sqrt((tp + fp) * (tp + fn) * (tn + fp) * (tn + fn))
    mcc_list.append(mcc)

In [28]:
mcc_list

[0.7841012471133944,
 0.8737407244049437,
 0.8842686149547753,
 0.9271556820342349,
 0.8958553041951381,
 0.9283444142985516,
 0.8560438075211538,
 0.6656864720978841,
 0.0918966092155373,
 0.736938376092473]

In [36]:
columns = ["accuracy", "precision", "recall", "f1", "specificity", "mcc"]

In [37]:
index = ['PVP0',
           'PVP1',
           'PVP2',
           'PVP3',
           'PVP4',
           'PVP5',
           'PVP6',
           'PVP7',
           'PVP8',
           'PVP9']

In [38]:
matrics = [np.array(accuracy_list),
           np.array(precision_list),
           np.array(recall_list),
           np.array(f1_list),
           np.array(specificity_list),
           np.array(mcc_list)]

In [39]:
matrics

[array([0.8842, 0.9341, 0.9403, 0.9637, 0.9463, 0.9639, 0.9273, 0.8056,
        0.5426, 0.8554]),
 array([0.9754657 , 0.98812253, 0.904     , 0.95705634, 0.9880203 ,
        0.98369249, 0.95758176, 0.98991354, 0.53886533, 0.97536585]),
 array([0.80351796, 0.8873503 , 0.99382485, 0.97586078, 0.91055389,
        0.94816617, 0.90400449, 0.64277695, 0.99887725, 0.74831587]),
 array([0.88118202, 0.93502908, 0.9467867 , 0.96636709, 0.94770669,
        0.96560267, 0.93002214, 0.7794418 , 0.70006557, 0.84688691]),
 array([0.97680412, 0.98775773, 0.87886598, 0.94974227, 0.98732818,
        0.98195876, 0.9540378 , 0.99248282, 0.01890034, 0.97830756]),
 array([0.78410125, 0.87374072, 0.88426861, 0.92715568, 0.8958553 ,
        0.92834441, 0.85604381, 0.66568647, 0.09189661, 0.73693838])]

In [40]:
df_matrics = pd.DataFrame(matrics).T

In [41]:
df_matrics.columns = columns

In [42]:
df_matrics

accuracy  precision    recall        f1  specificity       mcc
0    0.8842   0.975466  0.803518  0.881182     0.976804  0.784101
1    0.9341   0.988123  0.887350  0.935029     0.987758  0.873741
2    0.9403   0.904000  0.993825  0.946787     0.878866  0.884269
3    0.9637   0.957056  0.975861  0.966367     0.949742  0.927156
4    0.9463   0.988020  0.910554  0.947707     0.987328  0.895855
5    0.9639   0.983692  0.948166  0.965603     0.981959  0.928344
6    0.9273   0.957582  0.904004  0.930022     0.954038  0.856044
7    0.8056   0.989914  0.642777  0.779442     0.992483  0.665686
8    0.5426   0.538865  0.998877  0.700066     0.018900  0.091897
9    0.8554   0.975366  0.748316  0.846887     0.978308  0.736938

In [43]:
df_matrics = df_matrics.set_index(pd.Index(index))

In [44]:
df_matrics

accuracy  precision    recall        f1  specificity       mcc
PVP0    0.8842   0.975466  0.803518  0.881182     0.976804  0.784101
PVP1    0.9341   0.988123  0.887350  0.935029     0.987758  0.873741
PVP2    0.9403   0.904000  0.993825  0.946787     0.878866  0.884269
PVP3    0.9637   0.957056  0.975861  0.966367     0.949742  0.927156
PVP4    0.9463   0.988020  0.910554  0.947707     0.987328  0.895855
PVP5    0.9639   0.983692  0.948166  0.965603     0.981959  0.928344
PVP6    0.9273   0.957582  0.904004  0.930022     0.954038  0.856044
PVP7    0.8056   0.989914  0.642777  0.779442     0.992483  0.665686
PVP8    0.5426   0.538865  0.998877  0.700066     0.018900  0.091897
PVP9    0.8554   0.975366  0.748316  0.846887     0.978308  0.736938

In [45]:
matrics_writer = pd.ExcelWriter('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data3/result/matrics.xlsx', engine='xlsxwriter')

In [46]:
df_matrics.to_excel(matrics_writer, sheet_name='matrics', index=True)

In [47]:
matrics_writer.save()

C:\Users\user\AppData\Local\Temp\ipykernel_8916\1575248946.py:1: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  matrics_writer.save()
